//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movies
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public string MovieImageURL { get; set; }
    }
}
